Enhancement of the deegree workshop
lat-lon/deegree-workshop pull request #2
Opened 2024-09-26 12:27 UTC by Diego-AS98

Updated the duration the deegree GmlLoader takes to load the data into the SqlFeatureStore, minor formatting changes of the read.me and updated docker compose environment.

2024-09-26 13:21 UTC, julianzz98 requested changes
Please check and address the comments

2024-09-26 13:21 UTC, julianzz98 commented on README.md
> +| `.env` | Used to set the necessery environment variables                                                                                                                                           |
Link needs to be restored from `https://docsriables/` to `https://docs.docker.com/compose/environment-variables/set-environment-variables/`.

2024-09-26 13:21 UTC, julianzz98 commented on README.md
> +    $ docker compose up
Remove $

2024-09-26 13:21 UTC, julianzz98 commented on README.md
> +  This version however opens all the logs, which can be confusing.
Remove whitespace at the beginning of the paragraph

2024-09-26 13:21 UTC, julianzz98 commented on README.md
> +  >**Info** With a slight chance in the command the logs can be observed easily. If any chances are made, look up the updated tutorials on https://docs.docker.com/compose/compose-application-model/
Use "change" instead of "chance", remove whitespace at the beginning of the paragraph. But I don't really understand the information in this context.

2024-09-26 13:21 UTC, julianzz98 commented on README.md
> +  The **prefered** command would be:
Remove whitespace at the beginning of the paragraph

2024-09-26 13:21 UTC, julianzz98 commented on README.md
> +    $ docker compose up -d
Remove $

2024-09-26 13:21 UTC, julianzz98 commented on README.md
> +    $ docker compose down
Remove $

2024-09-26 13:21 UTC, julianzz98 commented on README.md
> +    $ docker compose logs
Remove $

2024-09-26 13:21 UTC, julianzz98 commented on README.md
> +    $ docker compose ps
Remove $

2024-09-26 13:21 UTC, julianzz98 commented on README.md
> +## 4.1 TEAM Engine 5.x: http://localhost:8181/deegree-webservices
Remove link `http://localhost:8181/deegree-webservices`

2024-09-26 13:21 UTC, julianzz98 commented on README.md
> +
Remove empty line

2024-09-30 08:52 UTC, Diego-AS98 commented on README.md
> +
215 ?

2024-10-07 09:57 UTC, julianzz98 approved these changes

2024-10-07 09:57 UTC, merged